name: vp_ci

on:
  push:
    branches: [master]

jobs:
  build-job:       # This job runs in the build stage, which runs first.
    runs-on: ubuntu

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: "17"

      - name: Build with Maven
        run: mvn clean
