name: vp_ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  checkout_build_test_job:
    runs-on: ubuntu-latest
    # runs-on: vp
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Set up JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup maven
        uses: stCarolas/setup-maven@v5

      - name: Clean and install project
        run: mvn clean install

      - name: Break
        run: sleep 20

      - name: Run test
        run: mvn test

  package_into_docker_image_job:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: export image
        run: docker build . --tag vp
