name: vp_ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-job:    
    runs-on: ubuntu-latest
    steps:
        
      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: "17"
          
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5

      - name: clean up
        run: ./mvn clean
